### PR TITLE
Feat/rtmp support

### PR DESCRIPTION
**Pull request by luiscovelo**
Hi,

Following roadmap, i implmented the support for RTMP inputs using nginx + [rtmp module](https://github.com/arut/nginx-rtmp-module).

To test this feature
1. Startup the docker-compose and then a RTMP server it's running in 1935 port and `mosaic-video` as path;
  1.2. Example: rtmp://192.168.0.127/mosaic-video/streamKey
3. Generate a rtmp input using ffmpeg, i created an example to test, run theses commands below:

```sh 
chmod +x ./statics/rtmp/push.sh && cd ./statics/rtmp
```
```sh
./push.sh
```

In this example, will generate this rtmp url to use as input: `rtmp://localhost/mosaic-video/kansas`.

Best reguards.

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Hello @luiscovelo 

I think adding one more service is not the best approach here.

If supporting RTMP is a matter of changing the input. we can just document it as an available option, otherwise this project will grow uncontrollably.

What about adding an example of how to use the `URL` field in the docs?

**Comment by luiscovelo** [comment]
Hello, @mauricioabreu.

No problem, i implemented the rtmp server because I thought of my use case, I have at home 2 surveillance cameras that support the rtmp protocol,. but an rtmp server is required for it to connect and generate images.. 

As I already worked with Nginx + rtmp, I thought it would make it easier for anyone who wants to use the project with security cameras, to already make the server available, where the user would configure on their device the server url, thus generating a rtmp url for server as input in the mosaic. 

However i understand the concern to add more services within the project in which is not part of the main goal that would be to generate mosaics.

**Comment by mauricioabreu** [comment]
@luiscovelo thank you for understanding.

And thank you for your amazing contributions so far.

**Comment by luiscovelo** [comment]
@mauricioabreu, Anytime.

I'll close this pr and in another moment we update docs related to rtmp input option.

**Pull request closed without merging**
