### PR TITLE
Use env package to initialize config struct

### LINKED ISSUE #18: Use a lib to map environment variables
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, we are parsing env configs in a struct managed entirely by ourselves, calling `os.Getenv` without any kind of validation.

Some libs like [env](https://github.com/caarlos0/env) and [envconfig](https://github.com/kelseyhightower/envconfig) are designed to move away this burden from developers.

**Describe alternatives you've considered**
I did not consider any alternatives other than the ones above but feel free to bring your ideas.

### PR DESCRIPTION
**Pull request by Hoega**
Closes #18 

Use the [env pkg](github.com/caarlos0/env) to decode and assign the config struct.

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Hello @Hoega I asked other project members to review your PR. So far so good, thank you!

**Comment by luiscovelo** [comment]
Hello @Hoega,

I analyzed those packages that @mauricioabreu mentioned, but i missed the option to unmarshall another types like .yaml or .json files, even live watching changes file.

It would be more interesting we use a most versatility library to avoid refactor in the future.

Can you'd to analyze viper again or others libraries that make senses with our goal?

**Comment by mauricioabreu** [comment]
I don't think using files to configure env variables is a good option. I also think that Cobra is a hard lib to maintain (even if the sole purpose is fetching some environment variables). IMHO, the way @Hoega implemented it serves the purpose  very well.

**Comment by mauricioabreu** [comment]
Good job @Hoega

**Review by luiscovelo — CHANGES_REQUESTED** [review]
Hello, @Hoega,

Would be interesting, to add a simple validation as isNotEmpty at least, so we can trust a minimum of validation for now.

@mauricioabreu what do you think?

**Comment by Hoega** [comment]
> Hello, @Hoega,
> 
> Would be interesting, to add a simple validation as isNotEmpty at least, so we can trust a minimum of validation for now.
> 
> @mauricioabreu what do you think?

I could add a "required" tag or use a default value. What would you prefer? For the moment, if we enforce a required environment variable, the app crashes if it is missing.

```
[Fx] Error returned: received non-nil error from function "github.com/mauricioabreu/mosaic-video/internal/config".NewConfig
        /home/frouxel/mosaic-video/internal/config/config.go:25:
env: required environment variable "REDIS_HOST" is not set
[Fx] ERROR              fx.Invoke(github.com/mauricioabreu/mosaic-video/internal/worker.Run()) called from:
github.com/mauricioabreu/mosaic-video/cmd.NewRootCmd.Work.func1
```

**Comment by luiscovelo** [comment]
@Hoega,

Oh right, it's better to use `notEmpty`, because `required` validate only if is set and not if is empty, see [this](https://github.com/caarlos0/env?tab=readme-ov-file#not-empty-fields).

**Comment by luiscovelo** [comment]
Nice!

**Pull request merged**
